### ISSUE TITLE
IoT cart

### ISSUE THREAD

**Issue by ulno** [iotempire/iotempower#106]
This task is stuck as I need to find an Estonian speaker to go with me to our local Delta furniture guy

**Comment by ulno** [comment]
Imho, the only one in our team who speaks a  bit Estonian is @stenoe - but he does not work in Delta.

**Comment by ulno** [comment]
Eero is going to help

**Comment by mbz4** [comment]
#### can do some fancy labels when done :)

##### Icon:
![Image](https://github.com/iotempire/iotempower/assets/30321314/dd2cbee8-d040-429a-a029-4d68386ac8af)


##### GPT:

![Image](https://github.com/iotempire/iotempower/assets/30321314/4ecbd365-b0e8-462d-8574-c15baba3b2e8)

**Comment by ulno** [comment]
wheels are greenlit 2h of project are already used up, so 8h with orderign and moutning is probably appropriate - just for a future reminder: such a task consumes at least 8 hours work time

**Comment by ulno** [comment]
ordered handle and wheels, should be here by end of may

**Comment by mbz4** [comment]
ToDo:
- [ ] Cupholder
- [ ] Logo Spray
- [ ] Built-In network switch
- [ ] Built-In power extension cord
- [ ] shock dampers (can try window sealant)

**Comment by mbz4** [comment]
Otherwise this task done for now, can prepare second task for remaining To-Do
