### ISSUE TITLE
User Interface with many buttons don't appear when in the node1 folder

### ISSUE THREAD

**Issue by Natomac** [iotempire/iotempower#6]
Following the documentation of the First Node, when we first adopt/Initialize, a the UI with the buttons are not showing after clicking  on the user menu button on the right corner. Only getting a terminal prompt.

**Comment by ulno** [comment]
I assume that the node.js environment is not correctly installed.

What error is showing up when you run ```iot menu```?

**Comment by ulno** [comment]
It is kind of fixed with new installer, though node still makes trouble
