### ISSUE TITLE
Add M5 docs entry

### ISSUE THREAD

**Issue by mbz4** [iotempire/iotempower#74]
M5 driver support is a thing now but its not referenced in command.rst yet and would be nice to have it.

**Comment by ulno** [comment]
estimate [ulno]: 1h

**Comment by mbz4** [comment]
Working on a simple examples project docs entry for the m5stickc. It must be ready by June 10th for the cyber-innovation conference. .-

![Image](https://github.com/iotempire/iotempower/assets/30321314/306e41a0-7a54-4e5d-85e2-8238aee06b60)

Inspect it here: https://github.com/mbz4/iotempower/blob/master/doc/examples_help/m5stickc.rst

**Comment by mbz4** [comment]
thinking we should include an example node-red flow with an m5stickc integration demo; thoughts?
