### ISSUE TITLE
SCD4X CO2 Sensor Driver & Docs

### ISSUE THREAD

**Issue by mbz4** [iotempire/iotempower#98]
## Extend _support_ to include the _Sensirion SCD40 compact photoacoustic NDIR CO2 sensor_. 

**Tasks:**
- understand features, examples,
- test available drivers, 
- write, validate IoTempower bridge,
- document new driver,
- merge PR. 

Bare sensor module:
![Image](https://github.com/iotempire/iotempower/assets/30321314/04811d36-1079-490c-8412-e678c294d05f)

Module in use for this driver development and in local stock:
![Image](https://github.com/iotempire/iotempower/assets/30321314/0f1f9194-deea-4a56-820f-f074071cedca)

 
**Resources:**
- [git: embedded i2c scd4x driver](https://github.com/Sensirion/embedded-i2c-scd4x)
- [RPi i2c scd4x driver](https://github.com/Sensirion/raspberry-pi-i2c-scd4x)
- [platformio registry: scd4x drivers](https://registry.platformio.org/search?q=scd4x)
- [datasheet: scd4x](https://cdn.sparkfun.com/assets/d/4/9/a/d/Sensirion_CO2_Sensors_SCD4x_Datasheet.pdf)
- [aliexpress: scd40 i2c module board ~20-30eur (expected 70eur)](https://www.aliexpress.com/item/1005006304936128.html?spm=a2g0o.productlist.main.9.1e0a6776V3Pqoz&algo_pvid=68d6cf26-bf81-47e0-b1c3-458f1d51ddde&aem_p4p_detail=2024042303061116377363140402160007662053&utparam-url=scene%3Asearch%7Cquery_from%3A&search_p4p_id=2024042303061116377363140402160007662053_1)
- Promising - [PlatformIO: DFRobot_SCD4X](https://registry.platformio.org/libraries/dfrobot/DFRobot_SCD4X)
- [Adafruit SCD-40 - True CO2, Temperature and Humidity Sensor - STEMMA QT / Qwiic](https://www.adafruit.com/product/5187)

**Comment by mbz4** [comment]
Update: ended up testing daisy chained with SGP30, SHT30, ENS160 and AHT2X sensors together on the same board and same platformio project, felt convenient as the SCD4x official i2c library has a few calibration and offset features so it made sense to merge the project 

![Image](https://github.com/iotempire/iotempower/assets/30321314/345f2471-bdad-4b31-848f-369d44b4f7ce)

**Comment by mbz4** [comment]
Started with this library: [git: DFRobot_SCD4X](https://github.com/DFRobot/DFRobot_SCD4X)

**Comment by mbz4** [comment]
Tried available libraries for async measurement support but the sensor is not robust (plug/unplug test - measurements differ too much, unreliable). Digging deeper into sensirion scd4x library...

**Comment by mbz4** [comment]
There be whales here! 🥇 



![Image](https://github.com/iotempire/iotempower/assets/30321314/6871b04b-1bfa-453e-81ec-2b07aa6babb3)

**Comment by ulno** [comment]
Maybe link the bias ribbit finding here?
Maybe it could be solved with an IoTempower filter?
What about an initial PR to encourage more testers?

**Comment by mbz4** [comment]
> Maybe link the bias ribbit finding here?

[GMAC_2024_-_Ribbit_Network_Poster_-_White_BG_48_x_36_in.pdf](https://github.com/iotempire/iotempower/files/15393718/GMAC_2024_-_Ribbit_Network_Poster_-_White_BG_48_x_36_in.pdf)

+ Ribbit issue detailing their decision process narrowing down sensor options: https://github.com/Ribbit-Network/ribbit-network-frog-hardware/issues/103

> Maybe it could be solved with an IoTempower filter?

ribbit in the poster don't really state it as a linear steady state bias error... so do we just need to the `add the difference to each measurement to offset the error from reference sensor` (vaisala)? ... i think we need to test this over a variety of temp, humidity ranges + CO2 concentration levels to really show the behaviour; but the datasheet does show deviations in specific ranges for the scd4x: https://sensirion.com/media/documents/48C4B7FB/64C134E7/Sensirion_SCD4x_Datasheet.pdf

> What about an initial PR to encourage more testers?

Can do, but will have to then regress the updated landing page architecture diagram.

**Comment by mbz4** [comment]
https://github.com/iotempire/iotempower/pull/118
